### ISSUE TITLE
Could not find command "list".

### ISSUE THREAD

**Issue by angelaambroz** [dstein64/vimgolf#3]
Just pip installed and got this unexpected output:

```
❯ vimgolf list
Could not find command "list".
Deprecation warning: Thor exit with status 0 on errors. To keep this behavior, you must define `exit_on_failure?` in `VimGolf::CLI`
You can silence deprecations warning by setting the environment variable THOR_SILENCE_DEPRECATION.
```

Some specs:
```
vimgolf==0.2.1
Python 3.8.6
ruby 2.6.3p62
```

**Comment by dstein64** [comment]
That error message looks like it could be coming from the [official](https://github.com/igrigorik/vimgolf/tree/master/lib/vimgolf) Vimgolf client, which has no `list` command. The `list` command included in the Python client I wrote was inspired by [vimgolf-finder](https://github.com/kciter/vimgolf-finder).

`which vimgolf` could be used to see the path to the `vimgolf` client that's executed.

To use the Python version while retaining the Ruby version on your `PATH`, `which -a python` may indicate the Python version's path, or alternatively `python3 -m vimgolf` could be used.

**Comment by qeexodan** [comment]
@angelaambroz, I noticed that `vimgolf show` does not work for some challenges, due to [Issue #306](https://github.com/igrigorik/vimgolf/issues/306).

I'm putting in a workaround now, which should be ready shortly, and I'll follow-up here when it's ready.

**Comment by dstein64** [comment]
@angelaambroz, I noticed that vimgolf show does not work for some challenges, due to [Issue #306](https://github.com/igrigorik/vimgolf/issues/306).

I'm putting in a workaround now, which should be ready shortly, and I'll follow-up here when it's ready.

**Comment by dstein64** [comment]
I've updated `vimgolf` so that `vimgolf show` will work on challenges that are currently reporting `We're sorry, but something went wrong` on vimgolf.com.

```
# Install the latest vimgolf
pip3 install --upgrade --no-cache-dir vimgolf
```

After updating to `vimgolf==0.2.2`, `vimgolf show 55b18bbea9c2c30d04000001` now works.
